### ISSUE TITLE
[Bug] Critterproof doors dont stop shines or pips

### ISSUE THREAD

**Issue by tofof** [Zonkeeh/ONI-Mods#1]
**Steam Name**
[Tofof](https://steamcommunity.com/id/tofof/ )

**Operating System / System requirements**
Windows 10
ONI LU-366134

**Mod Version**
[19:16:55.189] [1] [INFO] [Zolibrary] [Zonkeeh] -> Successfully loaded the mod Critter Proof Doors with version 1.0.2

**Describe the bug**
Pips walk right through critterproof doors.
Shines fly right through critterproof doors.

**To Reproduce**

1. Put a critterproof door. 
2. Open it.
3. Put a pip.
4. See that it fails immediately.

**Expected behavior**
> Have you ever wanted to just say no to critters who kindly want to escape your enclosure? Especially whilst keeping the door open/auto/unlocked for your duplicants?
Expected critterproof doors to not allow critter passage while open.

**Screenshots**
![critterproof](https://user-images.githubusercontent.com/3980843/65395315-c7c8ca00-dd5e-11e9-946d-9893b2bd648f.gif)

**Output Log**
n/a

**Comment by Zonkeeh** [comment]
Looking into this now. I assume its due to the building cells being stored incorrectly.

**Comment by Zonkeeh** [comment]
Issue fixed and mod updated to version 1.0.3

**Comment by tofof** [comment]
You literally only changed the version in readme.md and nothing else.

Wasted my time downloading the version from the repository and using it as a local mod and testing it only to find it's still bugged because of course it is because you literally did nothing.

**Comment by Zonkeeh** [comment]
Rude... Download it from steam as that version is up to date. I did not have time to upload it to GitHub and the readme updates automatically with steam... How about instead of moaning your giant ass off you be appreciative of the modding community whom make mods for free and fun. Not to be shouted at by no good internet trolls. If you spent 5 seconds looking rather than moaning you would realise the last updated to the mods directory wasn't today and therefore nothing could've changed and thought hmmnnn.... maybe I should check the steam page. Consider all future requests by you ignored :D 

Good Evening...

**Comment by tofof** [comment]
Sorry. Didn't mean to bite a newbie.

Given how prolifically you are modding the game in useful ways (way to go, seriously, 🎉), you appeared to be someone well-versed in things like the basics of git, as I'll explain later, and I took you as being needlessly careless. I apologize, again. 

Some advice, genuinely trying to be helpful:

You should consider git's local repo to be the primary place where your code lives - not the working directory.

You should **try to commit frequently**; as frequently as you might be used to pressing 'ctrl+s' or upon a successful compilation, etc. The less frequently you commit, the further spaced out are the 'checkpoints' that you could easily revert to. A single commit that does a version bump and touches several unrelated files is a sign you're not committing frequently enough. 

For example, the removal of the config.json certainly was an independent step and shouldn't be bundled with the other changes. Neither should the AdvancedSpaceScanner changes in ONI-mods.sln. Also, **you'll want your commit messages to be more informative**; simply naming the mod and the version number won't tell you anything when you're later looking at your code and commit history wondering why you ever moved away from List in the first place. You would've been better off with a commit explaining why you moved from List to Dictionary, and a separate commit explaining the harmony debug tooling you're invoking. If you want to be extra helpful to a future version of you, even consider dropping a link to the documentation of the harmony features, particularly if they're using a modern documentation solution and you can ensure that your link will remain pointed at the docs for the version of the suite you used at that time.

**Once you're used to your local repo always containing the latest 'true' version of your codebase, then ideas like "upload[ing] it to GitHub" disappear.** You don't upload, you just `git push` your local repo state to your remote repo. You do have to upload to Steam. If anything, then, the expectation is that the Git repo will always be more current than an external service you have to upload to.

Please understand that I'm certainly not trolling; my bug reports to you thus far have been thorough and as complete as possible. I didn't go out of my way to find your GitHub, follow your issue template, explicitly copy from the output_log.txt (to bypass any potential confusion regarding Steam's tendancy to serve outdated versions), make and include a screenshot illustrating the unexpected behavior.... just because I want to jerk you around or insult you. **I did so to help you locate a specific problem, and ultimately to benefit all your other users.** Also, if you _actually_ think someone is trolling you, you won't want to feed them anything that lets them see they succeeded in pissing you off. 

It's unexpected that the readme will get a bump in version number committed and pushed, while again still leaving all that actual code out of the repo. It's even more unusual for a developer to bother going into GitHub to close an issue (with a comment about the fix being in the new version!) while leaving the Git repository out of date, not actually containing that fix. Please try to avoid doing so in the future; the easiest way to ensure this is impossible is to never close issues manually.** Instead, **use GitHub's awesome [issue references](https://help.github.com/en/articles/closing-issues-using-keywords#about-issue-references) feature, and simply include the appropriate text (e.g. "Resolves #1") to auto-close the issue named in the commit message**.

Instead of spotting any of that for rookie mistakes, as I should have, I took it as a sign of gross carelessness on your part, and reacted with a mix of incredulousness and frustration as a result. You didn't deserve that reaction, and I apologize. Of course, you couldn't see any justification for my frustration, since you had no way to know that I had already gone to the effort of redownloading the mod, reinstalling it, disabling all my other mods, loading a test environment, watching pips/shines cross again, re-screenshotting, and re-writing up all those findings --- because before I posted all of that I did, at that point, check your commits and discover that no, I didn't have the current version of the mod.

Please **don't** recommend "download it from steam as that version is up to date" to anyone, ever.

It's already well known in the ONI modding community that Steam often serves up outdated files even multiple days past an update. You and I, in fact, already went through exactly that with your _Set Default Deconstruct Layer_ mod, along with the other user reporting the same problems I was having. I see you've deleted those comments, so you'll just have to take my word on it that I was the fellow who posted all the output_log links, let you know you hadn't updated the FileAssembly version, and provided CRCs of the various files to help distinguish them, as well as confirming that you had indeed fixed the error. That you seemed unfamiliar with checksums, then, should also have helped alert me to be extra careful not to bite.

It was for that reason that I deliberately sourced the 'fixed' file from this repository, rather than Steam. As I said, it's very unusual that Steam would ever be ahead of the git repo, and there was every expectation of Steam serving up the old version for several more days.

If you're wondering what gives your newness away, the main thing is your commit history being completely empty until two weeks ago. The 'pro' badge, particularly in combination with that history, makes it very clear that you're making use of the GitHub Student Developer Pack. For what it's worth, I did not take your apparent youth in your user photo into consideration, as that's rather a poor indicator of proficiency. 

I hope you'll tolerate one last observation. Your readme and Steam versioning place CritterProofDoors at 1.0.3. However, in your commit you updated the file assembly to 1.0.4, which is the version embedded in the DLL and displayed by the better mod managers. You'll probably want to resynchronize them.

**Comment by Zonkeeh** [comment]
Omg dude its a hobby, im well versed in git just have no fucking time right no for your crap...
