### ISSUE TITLE
Mod doesnt work on already analysed geyser/vent.

### ISSUE THREAD

**Issue by Slothy4K** [Zonkeeh/ONI-Mods#2]
Slothy4K

Win 10

1.0.2.0

Mod doesnt work on already analysed geyser/vent. If you analyse it after mod installation, it works fine

**Comment by Zonkeeh** [comment]
Fixed and tested in version 1.0.3 (currently processing), if the problem still persists please reopen.

**Comment by Slothy4K** [comment]
Still doesnt work for me, and how do i reopen a topic?? ^^
