### ISSUE TITLE
Metal Volcano loses Analysis

### ISSUE THREAD

**Issue by Slothy4K** [Zonkeeh/ONI-Mods#3]
Slothy4K

Win 10

1.0.3.0

After Installing or updating the mod, my iron volcano lost its analysis.
Only testet on iron volcano.

**Comment by Zonkeeh** [comment]
Please could you give some more information about this? I.e. did you have any output log errors etc. As just 1 line of explanation gives me little to look into.

**Comment by Slothy4K** [comment]
After searching may Install and documends files, even after some googleing i difnt find a single .log (exept depug) which file do you need??

**Comment by Zonkeeh** [comment]
AppData\LocalLow\Klei\Oxygen Not Included\output_log.txt

**Comment by Zonkeeh** [comment]
That is if it contains any relevant information such as errors etc.

**Comment by Zonkeeh** [comment]
Were you able to re-analyse the feature after launching? or was it just totally bugged?

**Comment by Slothy4K** [comment]
video and log from the video
https://youtu.be/Mettx-n8BwI
[output_log.txt](https://github.com/Zonkeeh/ONI-Mods/files/3670480/output_log.txt)

**Comment by Slothy4K** [comment]
and how do i reopen a report?? first bug ist still a issue

**Comment by Slothy4K** [comment]
ok. i did some testing myself after i had some thougts myself. "what if there wasnt a problem with loading, just with saving." then i remembert that i had mods installed. i disabled all mods only DF enabled. bug still existsing (yea, i know that i should have dne that first^^)

**Comment by Zonkeeh** [comment]
Interesting, I've tesed it on my end (for both) and I cannot replicate this. I will look into this at the weekend. For now you could change the config time for anaylsis to be very short. Apologies for this as I work during the week.

**Comment by Slothy4K** [comment]
its fine. i now how it is^^ im happy to help

**Comment by Slothy4K** [comment]
Workaround!
Disable mod. 
load map
analyse geyser
save map
enable mod
fix!!
well just that i still have the first bug

**Comment by Rodg88** [comment]
That workaround does work for saving the analyzed state of a geyser, but when I re-enable the mod, I can't analyze the geysers that were analyzed without the mod active.

**Comment by Rodg88** [comment]
[output_log.txt](https://github.com/Zonkeeh/ONI-Mods/files/3693985/output_log.txt)
That's the log from loading a save where a geyser was just analyzed. When I loaded the save, it was no longer analyzed. (I can't see anything obvious in the log myself)

**Comment by Slothy4K** [comment]
yea i have the same issue and already reported the bug. i think zonkeeh is already working on that

**Comment by Zonkeeh** [comment]
So to summarise what are the bugs?
    - Analysed state not saving
    - Deconstruct not showing?

**Comment by Rodg88** [comment]
Yep, with mod installed:
Newly analyzed geysers don't save analysed state
Deconstruct option not showing on geysers that were analysed before the mod was activated.

Also during testing I found editing the config to set analyse time to something other than default time results in analysis progress not progressing at all. The progress bar just stays black.
