### ISSUE TITLE
[Bug] Sweepy Conveyor output not working

### ISSUE THREAD

**Issue by hbpateiv** [Zonkeeh/ONI-Mods#35]
**Steam Name**
Your current steam name (and link to profile).
hbpateiv
https://steamcommunity.com/id/hbpateiv/

**Operating System / System requirements**
What system are you running and with what OS?
Windows 10

**Mod Version**
Your current version of the mod (found in output log)
1.0.1

**Describe the bug**
The sweepy station is not outputting to conveyor rails.

**To Reproduce**

I tried on multiple saves to get a different result, but each time it does not output. I attempted to build a new station and same result. I did not start a new game due to game time before it becomes available.

**Expected behavior**
Output station contents to conveyor rails.

**Screenshots**
![sweepy_bug_01](https://user-images.githubusercontent.com/7071261/81627697-c242f180-93cc-11ea-96b1-06d0b2aff20f.png)

**Additional context**
[ConfigCopy.txt](https://github.com/Zonkeeh/ONI-Mods/files/4612853/ConfigCopy.txt)

**Output Log**
If applicable please copy and paste your _output_log.txt_ contents that are relevant here.
[output_log.txt](https://github.com/Zonkeeh/ONI-Mods/files/4612854/output_log.txt)

**Comment by Zonkeeh** [comment]
Will look into this on the weekend. I am aware of a patch since making this mod that has changed some fo the base configuration for sweepy stations.

**Comment by hbpateiv** [comment]
Just in case you missed it, another user on the steam workshop comments replied with a way they were able to get it to work. However, per their words, it is dangerous to use in the way they were able to get it to work. I didn't know if this would help you in finding a solution but figured I add it regardless.

> Calavera Loca Jun 13 @ 5:45pm 
Hi,
Just the mod I was looking for!
I found the bug with the conveyor system. The dock has 2 Storages and the code assumes only one or at least the GetComponent<Storage>() always returns the first one which is the 25kg storage used to build the sweepy. So I replaced it with the quite unsafe GetComponents<Storage>()[1]. Also I requestes and assigned the same component to the custom 'stationdispenser's' storage variable to be safe.

**Comment by Bokonon-ONI** [comment]
I am having the same issue.  I forked your repo Zonkeeh, I decompiled the mod from Steam to get your Zolibrary which is not in your repo and got it to build.  I implemented the change suggested on Steam and copied here above but got a black hole crash when loading a save.

If you can give me a little guidance I'd love to fix and test it and send you a merge request.  I grabbed this mod for the sole purpose of using the conveyor output and it seems to be one thing not working.

My use is really simple, I'm trying to convey the contents to a simple chute and dump it on one tile.  Literally the green output on the dock connected directly to the chute.  Nothing merging in, nothing crossing.  I added a conveyor bridge in case for some reason it didn't know which direction to go.  Nothing works.

I'm on the Discord if you want to reach out, again I'm hoping you can point me in a direction to fix this myself and save me some effort in reverse engineering 😃.

**Comment by isochronous** [comment]
To anyone looking for an answer, @Bokonon-ONI put together his own mod ([piped sweepy's dock](https://steamcommunity.com/sharedfiles/filedetails/?id=2215668681)) that solves this problem, and any configuration changes you make via Zonkeeh's mod are actually applied to that dock.  I'd just recommend NOT enabling piped output in Zonkeeh's config, as the piped sweepy's dock will have that output by default.
