### ISSUE TITLE
[Bug] Duplicant Lifecycles locks out vanilla traits

### ISSUE THREAD

**Issue by bigestv** [Zonkeeh/ONI-Mods#39]
**Steam Name**
bigestv

**Operating System / System requirements**
Windows 10

**Mod Version**
1.0.7.4

**Describe the bug**
Reported by steam user Friendly
Using the Neuro Vacilitator with this mod active only allows for the Immortal trait to be awarded. Any subsequent uses give the message saying that all traits have been applied and that you can't improve upon perfection. This locks out the vanilla traits. The workaround is to disable the mod and apply the other traits.

**To Reproduce**
1. Use another Neuro Vacilitator with same dupe.

**Expected behavior**
A random vanilla trait is added to dupe.

**Screenshots**

**Additional context**

**Output Log**
If applicable please copy and paste your _output_log.txt_ contents that are relevant here.

**Comment by Zonkeeh** [comment]
Fixed in latest update!
