### ISSUE TITLE
[Advanced Space Scanner] Footprint is HUGE.

### ISSUE THREAD

**Issue by TroublesomeCorvid** [Zonkeeh/ONI-Mods#43]
Just as the title says.  I cannot place any kind of building within three tiles of the scanner.  But what's even worse is that this is reflected in the required footprint area - I also have to have three tiles of floor or ground to either side.  They cannot be doors of any kind because the moment they open, the scanner becomes useless.

I don't think there is any other building in the game that demands a floor space of ten tiles in order to function, vanilla or otherwise.  Not even the Monument.

I think I see what you're trying to do with it, though - you want those three tiles on either side to stay clear so buildings don't mess with the animation of the bunker-dome opening, right?  Perhaps a segmented bunker shell (like a pill bug's shell) would be better?

**Comment by Zonkeeh** [comment]
@TroublesomeCorvid I've changed the footprint to 6x5 now.
