### ISSUE TITLE
Crash related to mod "Wireless Power"

### ISSUE THREAD

**Issue by fleeting-aardvark** [Zonkeeh/ONI-Mods#45]
Game crashed with the following information:
```
NullReferenceException

UnityEngine.Component.GetComponent[T] () (at <b8388ffefd6046f8a7b4080349da72eb>:0)
WirelessPower.Components.WirelessPowerSender_WattsNeededWhenActive_Patch.Postfix (EnergyConsumer& __instance, System.Single& __result) (at <7173400f5fd244d5bf50ea26cc8962ec>:0)
(wrapper dynamic-method) EnergyConsumer.get_WattsNeededWhenActive_Patch1(object)
CircuitManager.GetWattsNeededWhenActive (System.UInt16 circuitID) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
Wire.<OnPrefabInit>b__19_0 (System.String str, System.Object data) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
StatusItem.ResolveString (System.String str, System.Object data) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
StatusItem.GetName (System.Object data) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
StatusItemGroup+Entry.GetName () (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
(wrapper dynamic-method) SelectToolHoverTextCard.UpdateHoverElements_Patch0(object,System.Collections.Generic.List`1<KSelectable>)
InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
InterfaceTool.LateUpdate () (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
```
Honestly, I cannot even tell you what happened.  I think I was deconstructing a wireless receiver, but it was off screen when the crash happened.  Please let me know if you need further details.

**Comment by TheShadowEevee** [comment]
I know this doesn't help much, but the Steam Workshop page has a very similar report you can look at, with some information from Zonkeeh.

https://steamcommunity.com/workshop/filedetails/discussion/2356326908/3106888345350327719/

**Comment by fleeting-aardvark** [comment]
Looks like it just happened again.

```
NullReferenceException

UnityEngine.Component.GetComponent[T] () (at <b8388ffefd6046f8a7b4080349da72eb>:0)
WirelessPower.Components.WirelessPowerSender_WattsNeededWhenActive_Patch.Postfix (EnergyConsumer& __instance, System.Single& __result) (at <7173400f5fd244d5bf50ea26cc8962ec>:0)
(wrapper dynamic-method) EnergyConsumer.get_WattsNeededWhenActive_Patch1(object)
CircuitManager.GetWattsNeededWhenActive (System.UInt16 circuitID) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
Wire.<OnPrefabInit>b__19_0 (System.String str, System.Object data) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
StatusItem.ResolveString (System.String str, System.Object data) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
StatusItem.GetName (System.Object data) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
StatusItemGroup+Entry.GetName () (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
(wrapper dynamic-method) SelectToolHoverTextCard.UpdateHoverElements_Patch0(object,System.Collections.Generic.List`1<KSelectable>)
InterfaceTool.UpdateHoverElements (System.Collections.Generic.List`1[T] hits) (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)
InterfaceTool.LateUpdate () (at <928dd3dd96c64d8a90b5e5d702b81a19>:0)

```

This time, I believe my duplicants were destroying some power cables.  And while I did not catch it last time {forgot to note it}, it looks like the related mods that are marked red to disable are: "Better Info Cards", "Wireless Power", "Drag Tool Area", and "Thermal Tooltips"

**Comment by TheShadowEevee** [comment]
Hmm... I may not be able to help much but this may narrow it down. 
Upload the files output_log.txt and Player.log from the folder "%appdata%/../LocalLow/Klei/Oxygen Not Included" before you do anything else, as those may have more info, then try to replicate the error with only those 4 mods installed. If it happens again try once more with just Wireless Power installed. That should narrow it down to see if it's a mod conflict.
If you can replicate it in either of those other scenarios, it would help to upload those logs as well.

**Comment by Zonkeeh** [comment]
Thanks for letting me know, could you disable the other mods and just have wireless power on and try and replicate it, please? Still unsure if this is an issue caused with overlapping patches or a bug in my mod itself.

**Comment by Zonkeeh** [comment]
Should be fixed with latest version update!
