### ISSUE TITLE
[Bug] Wireless Power - Tooltip Crash

### ISSUE THREAD

**Issue by TheShadowEevee** [Zonkeeh/ONI-Mods#46]
**Steam Name**
Steam Name: TheShadowEevee
Profile: https://steamcommunity.com/id/TheShadowEevee

**Operating System / System requirements**
Windows 10

**Mod Version**
Wireless Power version 1.0.1

**Describe the bug**
When viewing info about the wireless power buildings, two of the status informants seem to be missing or pointing at a non-existent tooltip. The tooltips they try to display don't exist and try to pull info past what is accessible from the tooltip array.

**To Reproduce**
1. Build any Wireless Power mod device
2. Click on the device to pull up building info
3. Scroll over "Grid Power Available:" or "Battery Power Available:" under the Status dropdown
4. Crash - Index was outside the bounds of the array

**Expected behavior**
A tooltip to be displayed, or if none is needed simply for the game to not crash.

**Screenshots**
Instead of a screenshot I included a video that should better show the bug.
A screenshot would not be able to show much here.

Youtube Link (Unlisted Video) - https://youtu.be/hRoDBVAqcKs

**Additional context**
ONI Build CS-447596
Replicated using 2 different installs on 2 devices, using different Steam accounts.
All mods other than Wireless Power were disabled before reporting and the log acquired.
I would be happy to look into this myself as well, but at a glance I didn't see the Wireless Power mod in the repo although linked via the mod page.
(If it's important, I do not own the DLC and as such it is not installed.)

**Output Log**
Output log "Player.log" has been uploaded, and contains the needed info.
[Player.log](https://github.com/Zonkeeh/ONI-Mods/files/5825532/Player.log)

**Comment by TheShadowEevee** [comment]
Apparently Youtube age restricted the video, although there is nothing that would be against the community guidelines.

I have submitted an appeal, but if you would like me to upload it here in the meantime please let me know

**Comment by Zonkeeh** [comment]
It's cool, I'll take a look into this when I have time. Was there any specific sequence that caused it, as this functionality worked in my testing?

**Comment by TheShadowEevee** [comment]
Not that I could tell, just seemed to happen.

**Comment by Zonkeeh** [comment]
@TheShadowEevee Bug is fixed in the latest update.
