### ISSUE TITLE
Loading Config.json problem with "Wireless Power" mod

### ISSUE THREAD

**Issue by fleeting-aardvark** [Zonkeeh/ONI-Mods#47]
In the latest build just updated this evening, any wireless building can only be built with steel even if the option `"BuildUsesOnlySteel": false` is set.  Somewhat makes it difficult to build the things when I have got very little steel.

**Comment by Zonkeeh** [comment]
Good Morning, I can't seem to replicate this issue. What file are you changing and in what game version/folder. I have a feeling you may be changing the wrong config file as the file locations now differ for the base game/DLC.

**Comment by fleeting-aardvark** [comment]
Unless the configuration file location has been changed, I have always edited `"My Documents\Klei\OxygenNotIncluded\mods\Steam\2356326908\Config.json"`.  It happened on two different computers.

I am not sure how to determine which version it is though.
From the dll file, it is 17.1.2021.0.  It was the latest downloaded from yesterday right before I posted this problem.

**Comment by Zonkeeh** [comment]
Could you send your _Player.log_, please? I can't find the issue on my end so without further investigation on your part I can't really help.

**Comment by fleeting-aardvark** [comment]
Yes.
However in scanning the Player.log ahead of time, it looks like it is not loading my Config.json file.
{Had to rename it to upload it, FYI}.

I do not know how to fix that.

I will attempt an unsubscribe and resubscribe to the mod to see if that helps.
[Player.log](https://github.com/Zonkeeh/ONI-Mods/files/5840388/Player.log)
[Config.json.txt](https://github.com/Zonkeeh/ONI-Mods/files/5840390/Config.json.txt)

**Comment by fleeting-aardvark** [comment]
Still looks like the mod is not loading my Config.json file.

It is in the "\My Documents\Klei\OxygenNotIncluded\mods\Steam\2356326908" location.

Also, from the Player.log file, the version I am having problems with is v1.0.2.
Hopefully you can offer a suggestion on how to correct the problem.

**Comment by fleeting-aardvark** [comment]
In looking at the "updated" mod, it still does not load my configuration file.

```[21:18:30.565] [1] [INFO] Loading mod content DLL [Wireless Power:2356326908] (provides DLL, Animation)
[21:18:30.566] [1] [INFO] Loading MOD dll: WirelessPower.dll
[21:18:30.910] [1] [INFO] [Zolibrary] [Zonkeeh] -> Successfully loaded the mod WirelessPower with version 1.0.2
[21:18:30.935] [1] [INFO] [DEBUG] [WirelessPower] [Zonkeeh] -> CheckConfigVariables()
UseColourInStatusItems: False
MaxNumberOfChannels: 10
UseEnergyFalloff: True
CustomEnergyFalloffPercentage: 0.05
BatteryCapacity: 40000
BatteryJoulesLostPerSecond: 0.75
DefaultTransfer: 200
MinTransfer: 10
MaxTransfer: 5000
BuildUsesOnlySteel: True
BatteryBuildTime: 60
BatteryMaterialCost: 400
SenderReceiverBuildTime: 30
SenderReceiverMaterialCost: 200```

That is from the player.log.  My config.json file is not even being loaded from `"\My Documents\Klei\OxygenNotIncluded\mods\Steam\2356326908\Config.json"`.

I do not have the DLC as you made a comment in the mod comments for the last update.  Maybe that could be the issue?

**Comment by Zonkeeh** [comment]
So here is the problem, if you're using the vanilla version of the game you must edit/store the config in the archived version folder as that is where ONI looks for it's config. This is something that I can't personally change for now.

**Comment by Zonkeeh** [comment]
i.e. `\My Documents\Klei\OxygenNotIncluded\mods\Steam\2356326908\archived_versions\vanilla_449546\Config.json` is loaded in the latest mod version. Not the config file you specified; that would be for the DLC version.

**Comment by fleeting-aardvark** [comment]
Thank you for clarifying that.  I would request that information be added to the mod information page, but that is your decision.
