### ISSUE TITLE
Potential "Wireless Power" mod infinite power issue [Bug]

### ISSUE THREAD

**Issue by fleeting-aardvark** [Zonkeeh/ONI-Mods#48]
I am using Windows 10, with mod version "vanilla_447596"

Another player {reNever} posted the following comment, "Hello, I think I found a bug while playing mod. If the receiver and sender are connected together by wires, and the power of the sender is reduced (for example, 10W), and then a power generation equipment is used to drive the whole power grid to run, then if the power generation equipment is removed, the whole power grid will also have continuous power input, and even a receiver can be connected with multiple sender, so that the battery can be filled instantly." on Jan 11 @ 8:27am.

I believe that I have a similar issue, or maybe more information on that particular bug.  I had a 'Sender' building with two smart batteries separated from the grid sending that power to the main grid with a 'Receiver' building on the main grid.  The sending grid drained very slowly, but the receiving "main" grid got to max power and never drained.  This was even after I created multi smart batteries to soak up all of this "sudden" extra power that was being generated.

Separately, I created a 'Sender' building and 'Receiver' building on the same grid {for trying to recreate the issue}.  Transfer rate does not seem to matter as I had it set to whatever the maximum setting was.  I noticed the issue after a reload of the game.  The grid power kept increasing even with no power generation going on.  I was able to stop the infinite power by changing the channel on the 'Receiver' building.  I am not entirely sure how it starts, but having both buildings on the same grid seems to get it started.

As a side note, this might be fixed in the current release as I am using one version back due to the configuration file not loading my settings correctly on the latest version.

[Player.log](https://github.com/Zonkeeh/ONI-Mods/files/5861474/Player.log)

**Comment by Zonkeeh** [comment]
Should be resolved in 1.0.3 as now more than one Receiver or Sender can be on the same circuit.
